// Mocks generated by Mockito 5.4.4 from annotations
// in hotelapp/test/feature/manger_dashboard/presentation/logic/manager_dashboard_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:hotelapp/core/networking/api_result.dart' as _i3;
import 'package:hotelapp/feature/manger_dashboard/data/models/reservation_model.dart'
    as _i6;
import 'package:hotelapp/feature/manger_dashboard/domain/repo/manager_dashboard_repo.dart'
    as _i2;
import 'package:hotelapp/feature/manger_dashboard/domain/user_cases/get_all_reservation_use_case.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeManagerDashboardRepo_0 extends _i1.SmartFake
    implements _i2.ManagerDashboardRepo {
  _FakeManagerDashboardRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResult_1<T> extends _i1.SmartFake implements _i3.ApiResult<T> {
  _FakeApiResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAllReservationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllReservationUseCase extends _i1.Mock
    implements _i4.GetAllReservationUseCase {
  MockGetAllReservationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ManagerDashboardRepo get managerDashboardRepo => (super.noSuchMethod(
        Invocation.getter(#managerDashboardRepo),
        returnValue: _FakeManagerDashboardRepo_0(
          this,
          Invocation.getter(#managerDashboardRepo),
        ),
      ) as _i2.ManagerDashboardRepo);

  @override
  _i5.Future<_i3.ApiResult<List<_i6.ReservationModel>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i5.Future<_i3.ApiResult<List<_i6.ReservationModel>>>.value(
                _FakeApiResult_1<List<_i6.ReservationModel>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.ApiResult<List<_i6.ReservationModel>>>);
}
